name: moler
channels:
  - rdkit
  - conda-forge
dependencies:
  - python==3.9.13
  - rdkit==2020.09.1.0
  - tensorflow==2.9.1
  - t2f_gnn==2.13.0
  - scikit-learn=0.24.1
  - protobuf==3.20
  - numpy
  - pandas
  - more-itertools
  - joblib==1.1.0
  - dpu-utils==0.2.13
